shared void run() {
    numbers();
    integer64Tests();
    preciseIntegerPowersOfTwo();
    integer64Power();
    integer64ToFloat();
    integer64ToCharacter();
    integer64ToByte();
    randomPlus();
    randomMinus();
    randomTimes();
    randomDivided();
    randomRemainder();
    randomModulo();
    randomPower();
    randomAnd();
    randomOr();
    randomXOr();
    randomRightArithmeticShift();
    randomLeftLogicalShift();
    randomGet();
    randomSetFalse();
    randomSetTrue();
    randomFlip();
    randomNot();
    randomNegated();
}