sudo: false
language: java
notifications:
  email: false
  pushover:
    on_failure: always
    on_success: change
    api_key:
      secure: M+fdp3yGig5OxkUSee2d/GI2TlzoNDae08hxOjrxt4dYqMRCaekBnS103ofXuj1h7MH2Qs5cUTPAaC+d+mQkH8XEuNSJ3KzKfaJP3Krs/Fzp+2wlp3+tget+PeCs7C9Jgjg1Yjq/4sErly5bmRyaptkgxYfEEEHsBO/EM3iKaU+GId6zQ8qRd9gN16MtKxYPWi0vKKTcuSCNzt/Vyj1+Csrl51IJme2ONZQpYszF0jYZCxVxNiv9NBBaAVtzk3aLLwyQ4hsmEFQXhzNTm/D4Z+fKbLipD3GIapXL0nr6nRCjLYpqgZD+ZxPihjt3X9Z6P8C9Ximi6I1dihg2qekk4Ow4XnMjRDSKTF6c9odC3sBIT1DlKF2GZkm4x2FoIENlG8i19YRoGS4sgxXZ9809BCI5Ixh7lZ5oENBYsQADxUF6bNobahic0yayLQPuJU7QBNiWoIkHF+NghZWznZs3fM5kqr7bsmuyiTRByUYqifKZElq2C0lJoWe+kzyO3IanJJG1xZbTpPT6wHjV9ega4NvahS07t+/TMFFGMkyaFi3z/+c2UiWPuAvE2S6DAZY2ahyjS8RcUUMMONhevtvXVYfDnLvrwnobU17jwem2BTAz7PQAwHIxco5FUfvRGyIRY44h9fKPzZHDDCBwgzES7s4m7w73p8szlRZmhWfsBcE=
    users:
      - secure: be0+yiF4DnpD67peRXDkZwWnlCvlmpNpPF6CYNShx1VsX6oqVjG3tE5Lr5R7Khe5Lf1/btAAQAIKF3e1gUm6BKLT67PAFD0rsqmtk1M6BwP8nkMlwEcO425ozGHXxPCwObLuDrt8cpmTuUoxxfwOc2QhwxExcsSr/Iz3D0AnyShxlKN/vIahxAb3aOGqbDkn4uVlFL4ZcP7IarD/TKo3lPJ2ngwyvjgjldzE8n7+l2Osw8m3GJ09R/et06UJCje9flIyA3WtkXXPqGQXX7XGJf0cVxK7/y1BAGNHEWgvZ53Jo5f5ZftjSUQQyGXiRb+l+WnDUCI6vpUHEXt3uk1cBmx9mmOEs3xIxTmUS0bd0kb1FRjQVF3F96qgl2XF7+oGFuOIc8Rauje7Onp71OpIjRvAUthSm9y3zy+Ht1vVLoEQUnGmSRodRPwjAgqXQkbgvFoFfOhOu+rG+V7cRvCqtvkKh8cammRClUDtwD8YTpSAjZGDodB7B7SYO0FiKETX2QTBxE87Xo5YuXM1ejKjFzNrGxnrS8ljCYrnUTQmyz+BBmPqNvnopQNBVT4KGTZA2zX98i0EToSNMI2uD/jQCth8vq2E0P3yryALOAA6dSIop1LlbCB2kzgLxJbheEJDlX3GcfqiiCogPOHnSk8D2bmpL2zKVYkJHQC07cn3fy0=
addons:
  artifacts:
    branch: master
    bucket: ceylon.vasileff.com
    target_paths: modules
    paths:
      - ./modules
    key:
      secure: T5/Wue2r4uLDUb6T5ZZLDC0Lnz55kU/7W5/c+rtMAEiZJxxVchX2fhyZeDK0hIUR7egoeob/JOYTtz7+MXpWS7s8z4HaTN3c5Zr1RlJ77/3Yw2CqLhSS/A/jpVHS3PEkLjGd1+V/s+NQRSPvPoZ9oZYz2nqEEhmQhL2KLVBQMqb1fOd31JZUpmatD+OgmNIStoLY6kWftrAzvKtA53tZe9l0NoWBiJ2aUVbsVAvh1Z7nNvevihv8q6ScfrxiZfH0J5z7xembYHXFSc04TJzugyhdTST62U8bktTJelfra8nNyilIShV51Kd7Ld5/C/uWHxuJaW/InbjbD37X7arDq+ELkHE9/o26R8eVtmkr9DC1PqEL8JIw+np8/OUZQaQ4WE29pFX5eApLXqQAxLPeCPvhOMWm+AmqmUcsb4OzVJRPcctH3Sg7owpELX3XhdGevaYpVqUBJTBfbiYJh9KfqJ1w0F1YKtD4HNVSFvlHr4aV0c9m2ZDe7TgJTO0pay50GZFtMFv0pJJoR4O3zKVLf+wurBVwGDXxhLGcK5ROvQ72QCcbUenE+4zm2rHYqiCMqFRa9ijM5s7IsirOCoI5ZN1MTOKvw/j5XTxIbcmygUcNcHZDWwgZDI8pIAOikZSvxZmM1qYa/B3VSZ2z7mOpD4O7nG5Zr53n+Q3HmjNpDV8=
    secret:
      secure: NpxzrMEViYbxbcFxREpz2SFMal42uesagiQ7efxQc7JuGzvoMwIRGJQ+qSYvkn97N3FecJdC3hm/5Jx+f+Im+Hg/LsUfFqz108K3zaJ1ticw4D4Hul8sGhExCosf1/MPTgwr5HbBivJG/9Ohg5W2tZqFxKh4JZrZTPQB7piCLU1qt2k/rKg2TNPU56C4yuWyYdwEOBP1XKGYW+nFGDTmNcg31jtLVr2vJ+FrQbbM/H8/jfFC8RTl/5oOW0Q8t3NOkNSSAjnRD8ovbwUUPaibpGQJ5Du7nezLiNcyds1Jnns/t8IFIBnLIZYMwkViKTmyCFWLgzt9biAZRhEu6QRjj5i10lSKB5GfgbJb68rFYUWIopgoRJpaEIwxqFYLDkgC7PCgTUybSSmeqVd+yNiBIkZqQBvjJ6o4j0scbCu+3EbgcGuks8IrV/VLy5BPWeByOG/TvaEMnMMR8BSqBnDLsf8JhR2A8VWyjhdlnVDbGBfDvlDrkHynKtQ+vUtmHLjmsRyp338a1BVp8L45Cb5CgAA5MOahEUSgkuMJ5qywFCG030cvBajdmcIW04OmvYCiM8kKQ1iHLpQMYkeVu5BS9cGpuOxP7OnGCXPQEUgyrpBjaO7iKE/sGnptEMmDJCK+un8u1R17ihNyU/HbDjwydYiP5tlvXJ9PG2XorIeOSIw=
jdk:
  - oraclejdk8
install:
  - wget --quiet --output-document=/tmp/ceylon.zip $CEYLON
  - unzip -q /tmp/ceylon.zip
  - export PATH=$PATH:$PWD/ceylon-1.3.2/bin/
  - export CEYLON_HOME=$PWD/ceylon-1.3.2
  - ceylon plugin install --force com.vasileff.ceylon.dart.cli/1.3.2-DP4
  - ceylon install-dart --out +USER
before_script:
  - ceylon compile,compile-js,compile-dart
script:
    - ceylon test,test-js $TEST_MODULE
env:
  global:
    - CEYLON="http://ceylon-lang.org/download/dist/1_3_2"
    - TEST_MODULE="test.com.vasileff.ceylon.integer64"

